CREATE DATABASE Blog_0;

CREATE TABLE Users (
    userID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    userName VARCHAR(100) NOT NULL,
    userEmail VARCHAR(200) UNIQUE NOT NULL,
    userPassword VARCHAR(100) NOT NULL,
    userRole ENUM('user', 'admin') NOT NULL,
    userCreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    userUpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Posts (
    postID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    postTitle VARCHAR(200) NOT NULL,
    postContent TEXT NOT NULL,
    userID INT UNSIGNED NOT NULL,
    postCreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    postUpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES Users(userID)
);

CREATE TABLE Comments (
    commentID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    commentContent TEXT NOT NULL,
    postID INT UNSIGNED NOT NULL,
    userID INT UNSIGNED NOT NULL,
    commentCreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    commentUpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (postID) REFERENCES Posts(postID),
    FOREIGN KEY (userID) REFERENCES Users(userID)
); 